"Generated by paket2bazel"

load(":paket.bdd_deps.bzl", _bdd_deps = "bdd_deps")

def _bdd_deps_impl(_ctx):
    _bdd_deps()

bdd_deps_extension = module_extension(
    implementation = _bdd_deps_impl,
)
